import{getPlaygroundModel}from"../../lib/playground-models";

type RunRequest={models?:unknown;system?:unknown;prompt?:unknown;temperature?:unknown;maxTokens?:unknown;format?:unknown};
const json=(value:unknown,status=200)=>Response.json(value,{status,headers:{"cache-control":"no-store","content-security-policy":"default-src 'none'","x-content-type-options":"nosniff"}});
const safeText=(value:unknown,max:number)=>typeof value==="string"?value.trim().slice(0,max):"";

async function runModel(modelId:string,system:string,prompt:string,temperature:number,maxTokens:number,format:string,endpoint:string,key:string){const model=getPlaygroundModel(modelId);if(!model)throw new Error("Model is not allowlisted");const started=Date.now();const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),45000);try{const response=await fetch(endpoint,{method:"POST",signal:controller.signal,headers:{"content-type":"application/json",authorization:`Bearer ${key}`,"http-referer":"https://axonradar.netlify.app","x-title":"AXON//RADAR Playground"},body:JSON.stringify({model:model.id,messages:[{role:"system",content:system},{role:"user",content:prompt}],temperature,max_tokens:maxTokens,...(format==="json"?{response_format:{type:"json_object"}}:{})})});const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(typeof body?.error?.message==="string"?body.error.message:`Provider returned ${response.status}`);const content=body?.choices?.[0]?.message?.content;const text=typeof content==="string"?content:Array.isArray(content)?content.map((item:{text?:string})=>item?.text??"").join(""):"";const inputTokens=Number(body?.usage?.prompt_tokens??0);const outputTokens=Number(body?.usage?.completion_tokens??0);return{modelId:model.id,name:model.name,provider:model.provider,status:"success",response:text||"The model returned an empty response.",latencyMs:Date.now()-started,inputTokens,outputTokens,cost:(inputTokens*model.inputPrice+outputTokens*model.outputPrice)/1_000_000}}finally{clearTimeout(timer)}}

export default async function handler(request:Request){if(request.method!=="POST")return json({error:"Method not allowed"},405);const origin=request.headers.get("origin");const allowed=origin===null||origin==="https://axonradar.netlify.app"||origin.startsWith("http://localhost:");if(!allowed)return json({error:"Origin not allowed"},403);let body:RunRequest;try{body=await request.json()}catch{return json({error:"Invalid JSON body"},400)}const models=Array.isArray(body.models)?[...new Set(body.models.filter((item):item is string=>typeof item==="string"))]:[];if(models.length<2||models.length>4||models.some(id=>!getPlaygroundModel(id)))return json({error:"Select two to four supported models"},400);const system=safeText(body.system,4000),prompt=safeText(body.prompt,12000);if(!prompt)return json({error:"Enter a prompt before running the comparison"},400);const temperature=Math.min(1,Math.max(0,Number(body.temperature)||0));const maxTokens=Math.min(1600,Math.max(100,Number(body.maxTokens)||600));const format=body.format==="json"?"json":"text";const openRouterKey=process.env.OPENROUTER_API_KEY,openRouterBase=process.env.OPENROUTER_BASE_URL,openAiKey=process.env.OPENAI_API_KEY,openAiBase=process.env.OPENAI_BASE_URL;const key=openRouterKey||openAiKey;const trimSlash=(value:string)=>value.endsWith("/")?value.slice(0,-1):value;const endpoint=openRouterKey&&openRouterBase?`${trimSlash(openRouterBase)}/chat/completions`:openAiKey&&openAiBase?`${trimSlash(openAiBase)}/v1/chat/completions`:"";if(!key||!endpoint)return json({error:"AI Gateway is not active for this deployment"},503);const settled=await Promise.allSettled(models.map(id=>runModel(id,system,prompt,temperature,maxTokens,format,endpoint,key)));const results=settled.map((result,index)=>result.status==="fulfilled"?result.value:{modelId:models[index],name:getPlaygroundModel(models[index])?.name??models[index],provider:getPlaygroundModel(models[index])?.provider??"",status:"error",response:"",latencyMs:0,inputTokens:0,outputTokens:0,cost:0,error:result.reason instanceof Error?result.reason.message:"Model request failed"});return json({results,ranAt:new Date().toISOString()})}

export const config={path:"/api/playground/run",rateLimit:{windowLimit:8,windowSize:60,aggregateBy:["ip","domain"]}};
