type HfModel={id:string;author?:string;lastModified?:string;downloads?:number;likes?:number;pipeline_tag?:string;tags?:string[];safetensors?:{total?:number};private?:boolean;gated?:boolean|string};
type ModelItem={id:string;name:string;provider:string;url:string;updatedAt:string;downloads:number;likes:number;task:string;parameters:number|null;sizeLabel:string;tier:"Frontier"|"Small"|"Mid-size"|"Unknown";access:"Open"|"Gated";tags:string[];source:"Hugging Face"};
const trustedFrontier=new Set(["meta-llama","google","mistralai","deepseek-ai","qwen","nvidia","ibm-granite","microsoft","tiiuae","moonshotai","zai-org","openai"]);
function extractParameters(model:HfModel){if(model.safetensors?.total)return model.safetensors.total;const text=`${model.id} ${(model.tags??[]).join(" ")}`;const matches=[...text.matchAll(/(?:^|[-_\s])([0-9]+(?:\.[0-9]+)?)\s*[bB](?:[-_\s]|$)/g)].map(match=>Number(match[1])*1e9);return matches.length?Math.max(...matches):null}
function tierFor(provider:string,parameters:number|null,name:string):ModelItem["tier"]{if(parameters!==null){if(parameters<=15e9)return"Small";if(parameters>=70e9)return"Frontier";return"Mid-size"}if(trustedFrontier.has(provider.toLowerCase())&&/(ultra|max|pro|reason|r1|large|opus|frontier)/i.test(name))return"Frontier";return"Unknown"}
function sizeLabel(parameters:number|null){if(parameters===null)return"Not disclosed";if(parameters>=1e12)return`${(parameters/1e12).toFixed(parameters%1e12?1:0)}T`;if(parameters>=1e9)return`${(parameters/1e9).toFixed(parameters%1e9?1:0)}B`;return`${Math.round(parameters/1e6)}M`}
const clean=(v:string)=>v.replace(/<!\[CDATA\[|\]\]>/g,"").replace(/<[^>]+>/g," ").replace(/&amp;/g,"&").replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/\s+/g," ").trim();
const tag=(xml:string,name:string)=>clean(xml.match(new RegExp(`<${name}[^>]*>([\\s\\S]*?)<\\/${name}>`,"i"))?.[1]??"");
async function frontierSignals(){const query='("new model" OR "model release") (OpenAI OR Anthropic OR Google DeepMind OR Meta AI OR Mistral OR DeepSeek OR Qwen) when:14d';const url=`https://news.google.com/rss/search?q=${encodeURIComponent(query)}&hl=en-US&gl=US&ceid=US:en`;const response=await fetch(url,{headers:{"User-Agent":"AI-Radar/2.0"},next:{revalidate:300}});if(!response.ok)return[];const xml=await response.text();return[...xml.matchAll(/<item>([\s\S]*?)<\/item>/gi)].slice(0,12).map(match=>{const block=match[1];const raw=tag(block,"title");const parts=raw.split(" - ");const source=parts.length>1?parts.pop()!:"Model news";return{title:parts.join(" - ")||raw,source,url:tag(block,"link"),publishedAt:new Date(tag(block,"pubDate")||Date.now()).toISOString()}}).filter(item=>item.title&&item.url)}
export async function GET(){try{const hfUrl="https://huggingface.co/api/models?pipeline_tag=text-generation&sort=lastModified&direction=-1&limit=100&full=true";const [hfResponse,signals]=await Promise.all([fetch(hfUrl,{headers:{Accept:"application/json","User-Agent":"AI-Radar/2.0"},next:{revalidate:300}}),frontierSignals().catch(()=>[])]);if(!hfResponse.ok)throw new Error("model registry unavailable");const raw=(await hfResponse.json()) as HfModel[];const models:ModelItem[]=raw.filter(model=>!model.private).map(model=>{const provider=model.id.split("/")[0]||model.author||"Community";const name=model.id.split("/").pop()||model.id;const parameters=extractParameters(model);return{id:model.id,name,provider,url:`https://huggingface.co/${model.id}`,updatedAt:model.lastModified??new Date().toISOString(),downloads:model.downloads??0,likes:model.likes??0,task:model.pipeline_tag??"text-generation",parameters,sizeLabel:sizeLabel(parameters),tier:tierFor(provider,parameters,name),access:model.gated?"Gated":"Open",tags:(model.tags??[]).filter(value=>!value.includes(":" )).slice(0,5),source:"Hugging Face"}}).sort((a,b)=>Date.parse(b.updatedAt)-Date.parse(a.updatedAt));return Response.json({models,signals,meta:{updatedAt:new Date().toISOString(),refreshSeconds:300,sources:["Hugging Face Hub","AI release coverage"]}},{headers:{"Cache-Control":"public, max-age=60, s-maxage=300, stale-while-revalidate=600"}})}catch{return Response.json({models:[],signals:[],meta:{updatedAt:new Date().toISOString(),refreshSeconds:300,sources:[]}},{status:200,headers:{"Cache-Control":"public, max-age=30"}})}}
