import type { Metadata } from "next";
import "./globals.css";
import "./routes.css";
import "./intel.css";
import "./sections-v2.css";
import "./news-fix.css";
import "./creators-polish.css";
import "./home-v3.css";
import "./home-theme-lock.css";
import "./seo-pages.css";
import "./benchmarks.css";
import "./compare-v2.css";
import "./playground.css";
import "./evaluations.css";
import "./router.css";
import "./operations.css";
import "./header-mobile-fix.css";
import "./footer-credit.css";
export const metadata:Metadata={metadataBase:new URL("https://axonradar.netlify.app"),title:{default:"AXON//RADAR — Live AI News, Models and Tools",template:"%s | AXON//RADAR"},description:"Track live AI news, frontier and open models, developer APIs, and creative AI tools. Compare free and paid options in one independent AI intelligence platform.",applicationName:"AXON//RADAR",authors:[{name:"Peyman Iravani",url:"https://github.com/eddieir"}],creator:"Peyman Iravani",publisher:"AXON//RADAR",category:"technology",keywords:["AI news","artificial intelligence news","AI models","frontier AI models","open source AI models","small language models","AI tools for developers","AI tools for creators","free AI tools","compare AI tools"],alternates:{canonical:"/",types:{"application/rss+xml":"/rss.xml"}},robots:{index:true,follow:true,nocache:false,googleBot:{index:true,follow:true,"max-image-preview":"large","max-snippet":-1,"max-video-preview":-1}},openGraph:{type:"website",locale:"en_US",siteName:"AXON//RADAR",url:"/",title:"AXON//RADAR — Live AI News, Models and Tools",description:"Live AI news, model intelligence, and practical tools for developers and creators.",images:[{url:"/og.png",width:1200,height:630,alt:"AXON//RADAR — AI intelligence, organized"}]},twitter:{card:"summary_large_image",title:"AXON//RADAR — Live AI News, Models and Tools",description:"Live AI news, model intelligence, and practical tools for developers and creators.",images:["/og.png"]},icons:{icon:[{url:"/favicon.ico?v=2",sizes:"any"},{url:"/favicon.svg?v=2",type:"image/svg+xml"}],shortcut:"/favicon.ico?v=2",apple:{url:"/apple-touch-icon.png?v=2",sizes:"180x180",type:"image/png"}},manifest:"/manifest.webmanifest"};
const structuredData={"@context":"https://schema.org","@graph":[{"@type":"Organization","@id":"https://axonradar.netlify.app/#organization","name":"AXON//RADAR","alternateName":"Axon Radar","url":"https://axonradar.netlify.app/","logo":{"@type":"ImageObject","url":"https://axonradar.netlify.app/og.png"},"founder":{"@type":"Person","name":"Peyman Iravani","url":"https://github.com/eddieir"},"sameAs":["https://github.com/eddieir"]},{"@type":"WebSite","@id":"https://axonradar.netlify.app/#website","url":"https://axonradar.netlify.app/","name":"AXON//RADAR","alternateName":"Axon Radar","description":"Live AI news, model intelligence, and practical tools for developers and creators.","publisher":{"@id":"https://axonradar.netlify.app/#organization"},"creator":{"@type":"Person","name":"Peyman Iravani","url":"https://github.com/eddieir"},"inLanguage":"en-US"}]};
export default function RootLayout({children}:Readonly<{children:React.ReactNode}>){return <html lang="en"><body>{children}<script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(structuredData).replace(/</g,"\\u003c")}}/></body></html>}
