import type { Metadata } from "next";
import "./globals.css";
import "./routes.css";
import "./intel.css";
import "./sections-v2.css";
import "./news-fix.css";
import "./creators-polish.css";
import "./home-v3.css";
import "./home-theme-lock.css";
export const metadata:Metadata={metadataBase:new URL("https://ai-radar-hub.eddieir.chatgpt.site"),title:{default:"AI Radar — Live AI News, Models and Tools",template:"%s | AI Radar"},description:"Track live AI news, frontier and open models, developer APIs, and creative AI tools. Compare free and paid options in one independent AI intelligence platform.",applicationName:"AI Radar",authors:[{name:"AI Radar"}],creator:"AI Radar",publisher:"AI Radar",category:"technology",keywords:["AI news","artificial intelligence news","AI models","frontier AI models","open source AI models","small language models","AI tools for developers","AI tools for creators","free AI tools","compare AI tools"],alternates:{canonical:"/"},robots:{index:true,follow:true,nocache:false,googleBot:{index:true,follow:true,"max-image-preview":"large","max-snippet":-1,"max-video-preview":-1}},openGraph:{type:"website",locale:"en_US",siteName:"AI Radar",url:"/",title:"AI Radar — Live AI News, Models and Tools",description:"Live AI news, model intelligence, and practical tools for developers and creators.",images:[{url:"/og.png",width:1200,height:630,alt:"AI Radar — live AI intelligence"}]},twitter:{card:"summary_large_image",title:"AI Radar — Live AI News, Models and Tools",description:"Live AI news, model intelligence, and practical tools for developers and creators.",images:["/og.png"]},icons:{icon:"/favicon.svg",shortcut:"/favicon.svg"},manifest:"/manifest.webmanifest"};
const structuredData={"@context":"https://schema.org","@graph":[{"@type":"Organization","@id":"https://ai-radar-hub.eddieir.chatgpt.site/#organization","name":"AI Radar","url":"https://ai-radar-hub.eddieir.chatgpt.site/","logo":{"@type":"ImageObject","url":"https://ai-radar-hub.eddieir.chatgpt.site/og.png"}},{"@type":"WebSite","@id":"https://ai-radar-hub.eddieir.chatgpt.site/#website","url":"https://ai-radar-hub.eddieir.chatgpt.site/","name":"AI Radar","description":"Live AI news, model intelligence, and practical tools for developers and creators.","publisher":{"@id":"https://ai-radar-hub.eddieir.chatgpt.site/#organization"},"inLanguage":"en-US"}]};
export default function RootLayout({children}:Readonly<{children:React.ReactNode}>){return <html lang="en"><body>{children}<script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(structuredData).replace(/</g,"\\u003c")}}/></body></html>}
