import Link from"next/link";import{SiteHeader}from"@/components/SiteHeader";import{SiteFooter}from"@/components/SiteFooter";import{ModelRadar}from"@/components/ModelRadar";import{HomeNewsBrief}from"@/components/HomeNewsBrief";import{getModelData}from"@/lib/model-data";import{getNewsData}from"@/lib/news-data";
export const dynamic="force-dynamic";
const paths=[
 {n:"01",label:"NEWS",title:"See what changed",copy:"Follow launches, research, policy, agents, creative AI, and industry movement.",href:"/news",tone:"cyan"},
 {n:"02",label:"MODELS",title:"Inspect what shipped",copy:"Track frontier, small, open-weight, gated, and commercial model activity.",href:"/models",tone:"lime"},
 {n:"03",label:"BENCHMARKS",title:"Measure the evidence",copy:"Review sourced quality, coding, agentic, and performance indicators.",href:"/benchmarks",tone:"paper"},
 {n:"04",label:"PLAYGROUND",title:"Test one real request",copy:"Run the same prompt across real models and compare answers, speed, tokens, and cost.",href:"/playground",tone:"violet"},
 {n:"05",label:"EVALUATIONS",title:"Test the pattern",copy:"Turn representative workloads into controlled, scored multi-model evaluations.",href:"/evaluations",tone:"cyan"},
 {n:"06",label:"ROUTER",title:"Operationalize the choice",copy:"Build explainable routing rules, cost guards, and resilient fallback chains.",href:"/router",tone:"lime"},
 {n:"07",label:"OPERATIONS",title:"Observe the system",copy:"Inspect real local reliability, latency, tokens, cost, fallbacks, traces, and budget signals.",href:"/operations",tone:"violet"},
 {n:"08",label:"DEVELOPERS",title:"Choose your stack",copy:"Compare APIs, runtimes, infrastructure, local AI, and agent platforms.",href:"/developers",tone:"paper"},
 {n:"09",label:"CREATORS",title:"Find production tools",copy:"Explore image, video, editing, design, audio, and post-production tools.",href:"/creators",tone:"violet"},
 {n:"10",label:"COMPARE",title:"Make the decision",copy:"Put quality, capabilities, access, privacy, and price in one view.",href:"/compare",tone:"cyan"}
];
const decisionWorkspaces=[
 {n:"03",label:"BENCHMARK INTELLIGENCE",title:"Evidence before opinion.",copy:"Sourced leaderboards, metric definitions, permanent model profiles, and explicit limitations.",href:"/benchmarks",cta:"OPEN BENCHMARKS"},
 {n:"04",label:"MULTI-MODEL PLAYGROUND",title:"One prompt. Real answers.",copy:"Select two to four executable models, compare output, latency, tokens, cost, and export the winner.",href:"/playground",cta:"RUN A LIVE TEST"},
 {n:"05",label:"EVALUATION STUDIO",title:"One answer is not evidence.",copy:"Build reusable datasets, run controlled batches, apply requirement checks and human scores, then export the report.",href:"/evaluations",cta:"BUILD AN EVALUATION"},
 {n:"06",label:"INTELLIGENT ROUTER",title:"Right request. Right model.",copy:"Simulate ordered policies locally, explain every decision, enforce budgets, and execute explicit fallbacks.",href:"/router",cta:"BUILD A ROUTER"},
 {n:"07",label:"AI OPERATIONS",title:"Keep the evidence visible.",copy:"Turn actual Router and Evaluation history into reliability, latency, token, cost, fallback, trace, and budget intelligence.",href:"/operations",cta:"OPEN OPERATIONS"}
];
const developerSignals=["FOUNDATION APIs","OPEN MODELS","AGENT RUNTIMES","LOCAL AI"],creatorSignals=["IMAGE","FILM + MOTION","EDIT + GRADE","AUDIO"];
export default async function Home(){const[modelData,newsData]=await Promise.all([getModelData(),getNewsData()]);return <><SiteHeader/><main className="home-v3" id="top">
 <section className="v3-hero"><div className="v3-hero-copy"><span className="v3-kicker"><i/>AI INTELLIGENCE, EVALUATION + ROUTING</span><h1>Know what<br/>matters in AI.<br/><em>Act faster.</em></h1><p>AXON//RADAR takes you from live signals to a production decision: follow the news, inspect models, examine evidence, run real tests, evaluate the workload, and route each request deliberately.</p><div className="v3-actions"><a href="#start-here">EXPLORE THE PLATFORM <span>↓</span></a><Link href="/playground">TEST REAL MODELS ↗</Link></div><div className="hero-proof"><span><b>LIVE</b> INTELLIGENCE</span><span><b>REAL</b> MODEL INFERENCE</span><span><b>CONTROLLED</b> EVALUATIONS</span><span><b>EXPLAINABLE</b> ROUTING</span></div></div><div className="v3-product-view"><div className="product-top"><span><i/>SYSTEM ONLINE</span><b>AXON//RADAR</b></div><div className="product-statement"><small>COMPLETE DECISION LOOP</small><h2>Discover.<br/>Evaluate.<br/><em>Route.</em></h2></div><div className="product-steps"><div><span>01</span><b>DISCOVER</b><small>News + models</small></div><div><span>02</span><b>PROVE</b><small>Benchmarks + evals</small></div><div><span>03</span><b>DEPLOY</b><small>Policies + fallbacks</small></div></div><div className="product-pulse"><span>10 CONNECTED WORKSPACES</span><i/><i/><i/><i/><i/><b>LIVE</b></div></div></section>
 <section className="start-guide" id="start-here"><div className="guide-head"><span>THE COMPLETE AXON//RADAR JOURNEY</span><h2>Start with the question.<br/><em>Finish with a decision.</em></h2><p>Follow the full sequence from current intelligence to deployment policy, or enter the workspace that matches your immediate task.</p></div><div className="guide-grid">{paths.map(path=><Link href={path.href} className={path.tone} key={path.n}><div><span>{path.n}</span><small>{path.label}</small></div><h3>{path.title}</h3><p>{path.copy}</p><b>OPEN WORKSPACE <i>↗</i></b></Link>)}</div></section>
 <section className="v3-news" id="latest-news"><div className="v3-section-head"><div><span>01 / NEWS</span><h2>See what changed<br/><em>while you worked.</em></h2></div><p>Current releases and research from official publishers and trusted technical sources—cleaned, classified, and linked to the original report.</p></div><HomeNewsBrief data={newsData}/><Link className="v3-wide-link" href="/news">ENTER THE FULL NEWSROOM <span>↗</span></Link></section>
 <section className="v3-models"><div className="v3-section-head"><div><span>02 / MODELS</span><h2>Track the models<br/><em>moving forward.</em></h2></div><p>Live model activity organized by scale, access, provider, and recency. Frontier launches and small open models belong in the same field of view.</p></div><ModelRadar compact initialData={modelData}/><Link className="v3-wide-link lime" href="/models">OPEN THE COMPLETE MODEL INDEX <span>↗</span></Link></section>
 <section className="home-decision-system"><header><span>03—07 / DECISION SYSTEM</span><h2>From “which model?”<br/><em>to “ship this policy.”</em></h2><p>Static rankings cannot answer a production question alone. AXON//RADAR connects evidence, controlled experiments, human judgment, and routing logic.</p></header><div>{decisionWorkspaces.map(workspace=><Link href={workspace.href} key={workspace.n}><span>{workspace.n} / {workspace.label}</span><h3>{workspace.title}</h3><p>{workspace.copy}</p><b>{workspace.cta} ↗</b></Link>)}</div><aside><span>THE LOOP</span><strong>Benchmark → Test → Evaluate → Route → Observe</strong><p>Use public evidence to shortlist. Use the Playground for a fast controlled comparison. Use Evaluations to test representative cases. Use Router to encode the winning operational decision. Use Operations to observe the result.</p></aside></section>
 <section className="home-capability-strip"><article><b>SOURCED</b><span>Benchmark evidence</span></article><article><b>REAL</b><span>Model responses</span></article><article><b>MEASURED</b><span>Latency, tokens + cost</span></article><article><b>HUMAN</b><span>Quality scoring</span></article><article><b>VISIBLE</b><span>Routing reasons</span></article><article><b>PORTABLE</b><span>Reports + configurations</span></article></section>
 <section className="v3-audience developer-band"><div className="audience-copy"><span>08 / DEVELOPERS</span><h2>Build with<br/><em>better context.</em></h2><p>Choose APIs, models, runtimes, and infrastructure by the decision you need to make—not by launch-day attention.</p><Link href="/developers">EXPLORE THE DEVELOPER STACK ↗</Link></div><div className="audience-grid">{developerSignals.map((item,index)=><div key={item}><span>{String(index+1).padStart(2,"0")}</span><b>{item}</b><i>↗</i></div>)}</div></section>
 <section className="v3-audience creator-band"><div className="audience-copy"><span>09 / CREATORS</span><h2>Keep the eye.<br/><em>Extend the craft.</em></h2><p>A production-minded index for photographers, filmmakers, editors, designers, and visual storytellers—organized by real creative work.</p><Link href="/creators">EXPLORE THE CREATIVE STACK ↗</Link></div><div className="audience-grid">{creatorSignals.map((item,index)=><div key={item}><span>{String(index+1).padStart(2,"0")}</span><b>{item}</b><i>↗</i></div>)}</div></section>
 <section className="v3-compare"><span>10 / COMPARE</span><div><h2>Less browsing.<br/><em>Better choosing.</em></h2><p>Compare models or tools in a consistent view across evidence, audience, category, pricing, access, capabilities, privacy, and strongest use cases.</p></div><Link href="/compare"><span>OPEN THE COMPARATOR</span><b>↗</b></Link></section>
 </main><SiteFooter/></>}
