"use client";
import Link from"next/link";import{useMemo,useState}from"react";import{benchmarkModels,metricInfo,type MetricKey}from"@/lib/benchmarks";

export function BenchmarkExplorer({initialMetric="intelligence" as MetricKey}){
 const[metric,setMetric]=useState<MetricKey>(initialMetric),[access,setAccess]=useState("All"),[query,setQuery]=useState("");
 const rows=useMemo(()=>benchmarkModels.filter(model=>(access==="All"||model.access===access)&&`${model.name} ${model.provider}`.toLowerCase().includes(query.toLowerCase())&&model.scores[metric]!==undefined).sort((a,b)=>(b.scores[metric]??0)-(a.scores[metric]??0)),[metric,access,query]);
 const best=rows[0]?.scores[metric]??1;
 const clear=()=>{setQuery("");setAccess("All")};
 return <div className="benchmark-explorer"><div className="benchmark-controls"><div className="metric-tabs">{(Object.keys(metricInfo)as MetricKey[]).map(key=><button type="button" key={key} className={metric===key?"active":""} onClick={()=>setMetric(key)}>{metricInfo[key].short}</button>)}</div><div className="benchmark-filter"><select aria-label="Filter by access" value={access} onChange={event=>setAccess(event.target.value)}><option>All</option><option>Proprietary</option><option>Open weights</option></select><input aria-label="Search models" value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search model or lab"/></div></div><div className="metric-definition"><div><span>ACTIVE MEASURE</span><h2>{metricInfo[metric].name}</h2></div><p>{metricInfo[metric].description} <Link href="/benchmarks/methodology">Methodology ↗</Link></p></div><div className="benchmark-table"><div className="benchmark-row benchmark-head"><span>RANK</span><span>MODEL</span><span>ACCESS</span><span>SCORE</span><span>RELATIVE</span><span/></div>{rows.map((model,index)=>{const score=model.scores[metric]??0;return <Link className="benchmark-row" href={`/benchmarks/models/${model.slug}`} key={model.slug}><span className="bench-rank">{String(index+1).padStart(2,"0")}</span><span className="bench-model"><b>{model.name}</b><small>{model.provider}</small></span><span><em className={model.access==="Open weights"?"open":""}>{model.access}</em></span><span className="bench-score"><b>{score}</b><small>{metricInfo[metric].unit}</small></span><span className="bench-bar"><i style={{width:`${Math.max(4,score/best*100)}%`}}/></span><span>↗</span></Link>})}{!rows.length&&<div className="search-empty" role="status"><span>NO MATCHING EVIDENCE</span><b>No benchmark models found.</b><p>Try a broader model or lab name, change the access filter, or clear the current search.</p><button type="button" onClick={clear}>CLEAR FILTERS</button></div>}</div><p className="benchmark-caveat">Ranks apply only to the selected evaluation and cited snapshot. Missing scores are not estimated. Harness, reasoning effort, provider, and version can materially change results.</p></div>
}
