"use client";
import{useEffect,useMemo,useState}from"react";
import{aggregateModel,defaultEvaluation,evaluationTemplates,resultKey,scoreRequirements,type EvaluationCase,type EvaluationResult,type EvaluationRun}from"@/lib/evaluations";
import{defaultPlaygroundModels,getPlaygroundModel,playgroundModels}from"@/lib/playground-models";
import{pluralize}from"@/lib/grammar";

const STORAGE="axon-radar-evaluation-runs-v1";
const uid=()=>Math.random().toString(36).slice(2,9);
const csvCell=(value:unknown)=>`"${String(value??"").replaceAll('"','""')}"`;
const download=(name:string,type:string,content:string)=>{const url=URL.createObjectURL(new Blob([content],{type}));const link=document.createElement("a");link.href=url;link.download=name;link.click();URL.revokeObjectURL(url)};

export function EvaluationStudio(){
 const[templateId,setTemplateId]=useState(defaultEvaluation.id);const[name,setName]=useState("Support model qualification");const[system,setSystem]=useState(defaultEvaluation.system);const[cases,setCases]=useState<EvaluationCase[]>(defaultEvaluation.cases);const[models,setModels]=useState(defaultPlaygroundModels);const[gatewayActive,setGatewayActive]=useState<boolean|null>(null);const[apiKey,setApiKey]=useState("");const[running,setRunning]=useState(false);const[progress,setProgress]=useState(0);const[current,setCurrent]=useState<EvaluationRun|null>(null);const[history,setHistory]=useState<EvaluationRun[]>([]);const[error,setError]=useState("");const[activeCase,setActiveCase]=useState(defaultEvaluation.cases[0].id);
 useEffect(()=>{fetch("/api/playground/run").then(response=>response.json()).then(body=>setGatewayActive(Boolean(body.gatewayActive))).catch(()=>setGatewayActive(false));Promise.resolve().then(()=>{try{const saved=JSON.parse(localStorage.getItem(STORAGE)??"[]");if(Array.isArray(saved))setHistory(saved.slice(0,12))}catch{}})},[]);
 const applyTemplate=(id:string)=>{const template=evaluationTemplates.find(item=>item.id===id);if(!template)return;setTemplateId(id);setName(template.name);setSystem(template.system);setCases(template.cases.map(item=>({...item,expectedTerms:[...item.expectedTerms]})));setActiveCase(template.cases[0].id);setCurrent(null)};
 const updateCase=(id:string,field:"name"|"prompt"|"expectedTerms",value:string)=>setCases(rows=>rows.map(row=>row.id===id?{...row,[field]:field==="expectedTerms"?value.split(",").map(term=>term.trim()).filter(Boolean):value}:row));
 const toggleModel=(id:string)=>setModels(selected=>selected.includes(id)?selected.length>2?selected.filter(item=>item!==id):selected:selected.length<4?[...selected,id]:selected);
 const saveRun=(run:EvaluationRun)=>{const next=[run,...history.filter(item=>item.id!==run.id)].slice(0,12);setHistory(next);localStorage.setItem(STORAGE,JSON.stringify(next))};
 const run=async()=>{if(cases.some(item=>!item.name.trim()||!item.prompt.trim())){setError("Every test case needs a name and a prompt.");return}setRunning(true);setError("");setProgress(0);const results:EvaluationResult[]=[];try{for(let index=0;index<cases.length;index++){const testCase=cases[index];const response=await fetch("/api/playground/run",{method:"POST",headers:{"content-type":"application/json",...(apiKey?{"x-openrouter-key":apiKey}:{})},body:JSON.stringify({models,system,prompt:testCase.prompt,temperature:0,maxTokens:700,format:"text"})});const body=await response.json();if(!response.ok)throw new Error(body.error||"Evaluation request failed");for(const row of body.results??[]){const requirement=scoreRequirements(row.response??"",testCase.expectedTerms);results.push({caseId:testCase.id,modelId:row.modelId,modelName:row.name,status:row.status,response:row.response,latencyMs:row.latencyMs,inputTokens:row.inputTokens,outputTokens:row.outputTokens,cost:row.cost,requirementScore:requirement.score,matchedTerms:requirement.matched,error:row.error})}setProgress(Math.round((index+1)/cases.length*100))}const completed:EvaluationRun={id:`eval-${Date.now()}-${uid()}`,name:name.trim()||"Untitled evaluation",createdAt:new Date().toISOString(),models,cases,results,manualScores:{},system};setCurrent(completed);saveRun(completed);setActiveCase(cases[0].id)}catch(reason){setError(reason instanceof Error?reason.message:"Evaluation could not run")}finally{setRunning(false)}};
 const rate=(caseId:string,modelId:string,value:number)=>{if(!current)return;const updated={...current,manualScores:{...current.manualScores,[resultKey(caseId,modelId)]:value}};setCurrent(updated);saveRun(updated)};
 const leaders=useMemo(()=>current?current.models.map(id=>aggregateModel(current,id)).sort((a,b)=>(b.manual||b.requirements/20)-(a.manual||a.requirements/20)):[],[current]);
 const exportJson=()=>current&&download(`${current.id}.json`,"application/json",JSON.stringify(current,null,2));
 const exportCsv=()=>{if(!current)return;const head=["case","model","status","requirements_percent","manual_score","latency_ms","input_tokens","output_tokens","cost_usd","response"];const rows=current.results.map(row=>[current.cases.find(item=>item.id===row.caseId)?.name,row.modelName,row.status,row.requirementScore,current.manualScores[resultKey(row.caseId,row.modelId)]??"",row.latencyMs,row.inputTokens,row.outputTokens,row.cost.toFixed(6),row.response].map(csvCell).join(","));download(`${current.id}.csv`,"text/csv",[head.join(","),...rows].join("\n"))};
 const activeRows=current?.results.filter(row=>row.caseId===activeCase)??[];
 return <div className="evaluation-studio">
  <section className="evaluation-setup"><header><span>01 / DEFINE THE EVALUATION</span><h2>Turn a real workload into a repeatable test.</h2><p>Start from a proven template or define your own cases. Every selected model receives the same system instruction, prompt, temperature, and output limit.</p></header><div className="template-grid">{evaluationTemplates.map(template=><button type="button" key={template.id} className={templateId===template.id?"active":""} onClick={()=>applyTemplate(template.id)}><small>{template.cases.length} TEST CASES</small><b>{template.name}</b><p>{template.description}</p><i>{templateId===template.id?"SELECTED ✓":"USE TEMPLATE →"}</i></button>)}</div>
  <div className="evaluation-fields"><label><span>EVALUATION NAME</span><input value={name} onChange={event=>setName(event.target.value)}/></label><label><span>SHARED SYSTEM INSTRUCTION</span><textarea value={system} onChange={event=>setSystem(event.target.value)}/></label></div>
  <div className="case-builder"><header><div><span>TEST DATASET</span><h3>{cases.length} controlled {pluralize(cases.length,"case")}</h3></div><button type="button" disabled={cases.length>=6} onClick={()=>{const id=uid();setCases(rows=>[...rows,{id,name:"New test case",prompt:"",expectedTerms:[]}]);setActiveCase(id)}}>+ ADD CASE</button></header>{cases.map((item,index)=><article key={item.id}><div className="case-number">0{index+1}</div><label><span>CASE NAME</span><input value={item.name} onChange={event=>updateCase(item.id,"name",event.target.value)}/></label><label className="case-prompt"><span>PROMPT</span><textarea value={item.prompt} onChange={event=>updateCase(item.id,"prompt",event.target.value)}/></label><label><span>EXPECTED TERMS <small>comma separated</small></span><input value={item.expectedTerms.join(", ")} onChange={event=>updateCase(item.id,"expectedTerms",event.target.value)}/></label><button type="button" disabled={cases.length<=1} onClick={()=>setCases(rows=>rows.filter(row=>row.id!==item.id))}>REMOVE</button></article>)}</div></section>
  <section className="evaluation-models"><header><span>02 / SELECT CONTENDERS</span><h2>Choose two to four real models.</h2><p>The complete dataset runs against every selected model. Lower the case count if you want a faster, cheaper first pass.</p></header><div>{playgroundModels.map(model=><button type="button" key={model.id} className={models.includes(model.id)?"active":""} onClick={()=>toggleModel(model.id)}><span>{model.tier} / {model.provider}</span><b>{model.name}</b><p>{model.note}</p><small>{model.inputPrice===0?"FREE ROUTE":`$${model.inputPrice}/M INPUT`}</small></button>)}</div></section>
  <section className="evaluation-run"><div className={`evaluation-connection ${gatewayActive?"active":""}`}><div><span>MODEL CONNECTION</span><b>{gatewayActive?"SITE AI GATEWAY READY":"OPENROUTER KEY REQUIRED"}</b><p>{gatewayActive?"Shared gateway access is active for this run.":"The site gateway is inactive. Your key stays in this tab's component memory and is not persisted."}</p></div>{!gatewayActive&&<label><span>OPENROUTER API KEY</span><input type="password" autoComplete="off" placeholder="sk-or-…" value={apiKey} onChange={event=>setApiKey(event.target.value)}/><a href="https://openrouter.ai/settings/keys" target="_blank" rel="noopener noreferrer">MANAGE KEY ↗</a></label>}</div><div className="run-summary"><div><span>03 / RUN CONTROLLED TEST</span><h2>{cases.length} {pluralize(cases.length,"case")} × {models.length} {pluralize(models.length,"model")}</h2><p>{cases.length*models.length} total answers · deterministic temperature · maximum 700 output tokens per answer</p></div><button type="button" onClick={run} disabled={running||gatewayActive===false&&!apiKey}>{running?`RUNNING ${progress}%…`:gatewayActive===false&&!apiKey?"ENTER A KEY TO RUN":"RUN FULL EVALUATION →"}</button></div>{running&&<div className="evaluation-progress"><i style={{width:`${progress}%`}}/><span>{progress}% COMPLETE</span></div>}{error&&<div className="evaluation-error" role="alert"><b>EVALUATION STOPPED</b><p>{error}</p></div>}</section>
  {current&&<section className="evaluation-report"><header><div><span>04 / EVALUATION REPORT</span><h2>{current.name}</h2><p>{new Date(current.createdAt).toLocaleString()} · {current.cases.length} cases · {current.models.length} models</p></div><nav><button type="button" onClick={exportJson}>EXPORT JSON</button><button type="button" onClick={exportCsv}>EXPORT CSV</button><button type="button" onClick={()=>window.print()}>PRINT REPORT</button></nav></header><div className="evaluation-leaderboard">{leaders.map((leader,index)=><article key={leader.modelId} className={index===0?"leader":""}><span>0{index+1}</span><h3>{leader.name}</h3><div><b>{leader.manual||"—"}</b><small>MANUAL / 5</small></div><div><b>{leader.requirements}%</b><small>TERM COVERAGE</small></div><div><b>{leader.passRate}%</b><small>COMPLETION</small></div><div><b>{leader.latency}ms</b><small>AVG LATENCY</small></div><div><b>${leader.cost.toFixed(4)}</b><small>TOTAL COST</small></div></article>)}</div><div className="case-tabs">{current.cases.map(item=><button type="button" className={activeCase===item.id?"active":""} onClick={()=>setActiveCase(item.id)} key={item.id}>{item.name}</button>)}</div><div className="evaluation-answers">{activeRows.map(row=><article key={row.modelId}><header><div><span>{getPlaygroundModel(row.modelId)?.provider}</span><h3>{row.modelName}</h3></div><div><b>{row.requirementScore}%</b><small>EXPECTED TERMS</small></div></header><div className="answer-metrics"><span><b>{row.latencyMs}ms</b>LATENCY</span><span><b>{row.inputTokens+row.outputTokens}</b>TOKENS</span><span><b>${row.cost.toFixed(5)}</b>COST</span></div>{row.status==="success"?<p className="evaluation-output">{row.response}</p>:<p className="evaluation-output error">{row.error}</p>}<footer><div><small>MATCHED</small><p>{row.matchedTerms.length?row.matchedTerms.join(" · "):"No expected terms matched"}</p></div><fieldset><legend>YOUR QUALITY SCORE</legend>{[1,2,3,4,5].map(value=><button type="button" key={value} className={current.manualScores[resultKey(row.caseId,row.modelId)]===value?"active":""} onClick={()=>rate(row.caseId,row.modelId,value)}>{value}</button>)}</fieldset></footer></article>)}</div></section>}
  <section className="evaluation-history"><header><span>SAVED IN THIS BROWSER</span><h2>Recent evaluation history</h2><p>Runs remain on this device until browser storage is cleared. Export JSON for a portable, auditable record.</p></header><div>{history.length?history.map(run=><button type="button" key={run.id} onClick={()=>{setCurrent(run);setCases(run.cases);setModels(run.models);setSystem(run.system);setName(run.name);setActiveCase(run.cases[0]?.id??"")}}><span>{new Date(run.createdAt).toLocaleDateString()}</span><b>{run.name}</b><small>{run.cases.length} CASES × {run.models.length} MODELS</small><i>OPEN REPORT →</i></button>):<p>No saved runs yet. Your first completed evaluation will appear here.</p>}</div></section>
 </div>
}
