"use client";
import{ChangeEvent,useEffect,useMemo,useRef,useState}from"react";

const ROUTER_RUNS="axon-radar-routing-runs-v1",EVAL_RUNS="axon-radar-evaluation-runs-v1";
type Trace={id:string;source:"Router"|"Evaluation";model:string;createdAt:string;status:"success"|"error";latency:number;tokens:number;cost:number;fallbacks:number;context:string};
type Thresholds={latency:number;dailyCost:number;errorRate:number;fallbackRate:number};
const initialThresholds:Thresholds={latency:8000,dailyCost:1,errorRate:5,fallbackRate:20};
const number=(value:unknown)=>typeof value==="number"&&Number.isFinite(value)?value:0;
const download=(name:string,content:string,type="application/json")=>{const url=URL.createObjectURL(new Blob([content],{type}));const link=document.createElement("a");link.href=url;link.download=name;link.click();URL.revokeObjectURL(url)};
const readLocal=():Trace[]=>{const traces:Trace[]=[];try{const router=JSON.parse(localStorage.getItem(ROUTER_RUNS)??"[]");if(Array.isArray(router))router.forEach((run,index)=>traces.push({id:`router-${run.createdAt??index}`,source:"Router",model:String(run.modelName??run.modelId??"Unknown model"),createdAt:String(run.createdAt??new Date().toISOString()),status:"success",latency:number(run.latencyMs),tokens:number(run.inputTokens)+number(run.outputTokens),cost:number(run.cost),fallbacks:Math.max(0,Array.isArray(run.attempts)?run.attempts.length-1:0),context:"Live routed request"}));const evaluations=JSON.parse(localStorage.getItem(EVAL_RUNS)??"[]");if(Array.isArray(evaluations))evaluations.forEach(run=>Array.isArray(run.results)&&run.results.forEach((result:Record<string,unknown>,index:number)=>traces.push({id:`evaluation-${run.id??run.createdAt}-${index}`,source:"Evaluation",model:String(result.modelName??result.modelId??"Unknown model"),createdAt:String(run.createdAt??new Date().toISOString()),status:result.status==="success"?"success":"error",latency:number(result.latencyMs),tokens:number(result.inputTokens)+number(result.outputTokens),cost:number(result.cost),fallbacks:0,context:String(run.name??"Evaluation run")})))}catch{}return traces.sort((a,b)=>Date.parse(b.createdAt)-Date.parse(a.createdAt))};
const csv=(rows:Trace[])=>["id,source,model,created_at,status,latency_ms,tokens,cost_usd,fallbacks,context",...rows.map(row=>[row.id,row.source,row.model,row.createdAt,row.status,row.latency,row.tokens,row.cost,row.fallbacks,row.context].map(value=>`"${String(value).replaceAll('"','""')}"`).join(","))].join("\n");

export function OperationsConsole(){const[traces,setTraces]=useState<Trace[]>([]),[source,setSource]=useState("All"),[thresholds,setThresholds]=useState(initialThresholds),[message,setMessage]=useState("");const input=useRef<HTMLInputElement>(null);
 useEffect(()=>{Promise.resolve().then(()=>setTraces(readLocal()))},[]);
 const visible=useMemo(()=>source==="All"?traces:traces.filter(trace=>trace.source===source),[traces,source]);
 const metrics=useMemo(()=>{const success=visible.filter(trace=>trace.status==="success"),cost=visible.reduce((sum,trace)=>sum+trace.cost,0),tokens=visible.reduce((sum,trace)=>sum+trace.tokens,0),fallbacks=visible.filter(trace=>trace.fallbacks>0).length;return{requests:visible.length,successRate:visible.length?success.length/visible.length*100:0,cost,tokens,latency:success.length?success.reduce((sum,trace)=>sum+trace.latency,0)/success.length:0,fallbackRate:visible.length?fallbacks/visible.length*100:0}},[visible]);
 const models=useMemo(()=>Object.entries(visible.reduce<Record<string,{runs:number;cost:number;latency:number;errors:number}>>((all,trace)=>{const row=all[trace.model]??{runs:0,cost:0,latency:0,errors:0};row.runs++;row.cost+=trace.cost;row.latency+=trace.latency;if(trace.status==="error")row.errors++;all[trace.model]=row;return all},{})).sort((a,b)=>b[1].runs-a[1].runs),[visible]);
 const alerts=[metrics.latency>thresholds.latency&&`Average latency is ${Math.round(metrics.latency)}ms, above the ${thresholds.latency}ms target.`,metrics.cost>thresholds.dailyCost&&`Observed cost is $${metrics.cost.toFixed(4)}, above the $${thresholds.dailyCost.toFixed(2)} workspace budget.`,100-metrics.successRate>thresholds.errorRate&&`Error rate is ${(100-metrics.successRate).toFixed(1)}%, above the ${thresholds.errorRate}% limit.`,metrics.fallbackRate>thresholds.fallbackRate&&`Fallback usage is ${metrics.fallbackRate.toFixed(1)}%, above the ${thresholds.fallbackRate}% limit.`].filter(Boolean) as string[];
 const refresh=()=>{setTraces(readLocal());setMessage("Local Router and Evaluation history refreshed.")};
 const importFile=async(event:ChangeEvent<HTMLInputElement>)=>{const file=event.target.files?.[0];if(!file)return;try{const body=JSON.parse(await file.text());const rows=(Array.isArray(body)?body:body.traces) as Trace[];if(!Array.isArray(rows))throw new Error();const valid:Trace[]=rows.filter(row=>row&&["Router","Evaluation"].includes(row.source)&&typeof row.model==="string"&&typeof row.createdAt==="string").map(row=>({...row,id:row.id||`import-${crypto.randomUUID()}`,status:(row.status==="error"?"error":"success") as Trace["status"],latency:number(row.latency),tokens:number(row.tokens),cost:number(row.cost),fallbacks:number(row.fallbacks)}));setTraces(current=>[...valid,...current]);setMessage(`${valid.length} portable traces imported into this view. They were not written into Router or Evaluation history.`)}catch{setMessage("Import failed. Choose an AXON//RADAR Operations JSON export.")}event.target.value=""};
 return <div className="ops-console"><section className="ops-control"><div><span>LOCAL TELEMETRY</span><h2>Your activity, not invented analytics.</h2><p>Operations reads completed Router dispatches and Evaluation results already stored in this browser. No account, tracking script, or fabricated global traffic is involved.</p></div><div className="ops-actions"><button type="button" onClick={refresh}>REFRESH LOCAL DATA</button><button type="button" onClick={()=>input.current?.click()}>IMPORT JSON</button><input ref={input} hidden type="file" accept="application/json" onChange={importFile}/><button type="button" disabled={!traces.length} onClick={()=>download("axon-radar-operations.json",JSON.stringify({version:1,exportedAt:new Date().toISOString(),traces},null,2))}>EXPORT JSON</button><button type="button" disabled={!visible.length} onClick={()=>download("axon-radar-operations.csv",csv(visible),"text/csv")}>EXPORT CSV</button></div>{message&&<p className="ops-message" role="status">{message}</p>}</section>
 <section className="ops-filters"><b>OBSERVABILITY WINDOW</b>{["All","Router","Evaluation"].map(item=><button type="button" className={source===item?"active":""} onClick={()=>setSource(item)} key={item}>{item.toUpperCase()}</button>)}<span>{visible.length} TRACE{visible.length===1?"":"S"}</span></section>
 {!traces.length?<section className="ops-empty"><span>NO LOCAL RUNS YET</span><h2>Create the signal first.</h2><p>Run a live request in Router or complete an Evaluation. Return here and refresh; the resulting latency, token, cost, model, status, and fallback evidence will appear automatically.</p><div><a href="/router">RUN THE ROUTER ↗</a><a href="/evaluations">START AN EVALUATION ↗</a></div></section>:<>
 <section className="ops-metrics"><article><span>REQUESTS</span><b>{metrics.requests}</b><small>OBSERVED TRACES</small></article><article><span>SUCCESS RATE</span><b>{metrics.successRate.toFixed(1)}%</b><small>{metrics.requests-Math.round(metrics.requests*metrics.successRate/100)} ERRORS</small></article><article><span>AVG LATENCY</span><b>{Math.round(metrics.latency)}<i>ms</i></b><small>SUCCESSFUL RUNS</small></article><article><span>TOKENS</span><b>{metrics.tokens.toLocaleString()}</b><small>INPUT + OUTPUT</small></article><article><span>COST</span><b>${metrics.cost.toFixed(4)}</b><small>PROVIDER REPORTED</small></article><article><span>FALLBACKS</span><b>{metrics.fallbackRate.toFixed(1)}%</b><small>ROUTER RUN SHARE</small></article></section>
 <section className="ops-grid"><div className="ops-models"><header><span>MODEL DISTRIBUTION</span><h3>Where the work went.</h3></header>{models.map(([name,row])=><article key={name}><div><b>{name}</b><span>{row.runs} RUNS · {row.errors} ERRORS</span></div><i style={{width:`${Math.max(4,row.runs/Math.max(...models.map(([,value])=>value.runs))*100)}%`}}/><small>{Math.round(row.latency/row.runs)}MS AVG · ${row.cost.toFixed(4)}</small></article>)}</div><div className="ops-alerts"><header><span>POLICY MONITOR</span><h3>{alerts.length?`${alerts.length} threshold alert${alerts.length===1?"":"s"}`:"Operating within limits."}</h3></header><div className="threshold-grid"><label>LATENCY / MS<input type="number" value={thresholds.latency} onChange={e=>setThresholds({...thresholds,latency:Number(e.target.value)})}/></label><label>BUDGET / USD<input type="number" step=".1" value={thresholds.dailyCost} onChange={e=>setThresholds({...thresholds,dailyCost:Number(e.target.value)})}/></label><label>ERROR RATE / %<input type="number" value={thresholds.errorRate} onChange={e=>setThresholds({...thresholds,errorRate:Number(e.target.value)})}/></label><label>FALLBACK RATE / %<input type="number" value={thresholds.fallbackRate} onChange={e=>setThresholds({...thresholds,fallbackRate:Number(e.target.value)})}/></label></div><div className="alert-list">{alerts.length?alerts.map(alert=><p key={alert}><b>!</b>{alert}</p>):<p className="clear"><b>✓</b>No configured threshold is exceeded.</p>}</div></div></section>
 <section className="ops-traces"><header><div><span>TRACE LEDGER</span><h2>Inspect every observed run.</h2></div><p>Newest first. Imported records exist in this view only and remain clearly portable.</p></header><div className="trace-table"><div className="trace-head"><span>TIME</span><span>SOURCE / CONTEXT</span><span>MODEL</span><span>STATUS</span><span>LATENCY</span><span>TOKENS</span><span>COST</span><span>FALLBACKS</span></div>{visible.map(trace=><article key={trace.id}><time>{new Date(trace.createdAt).toLocaleString()}</time><div><b>{trace.source}</b><small>{trace.context}</small></div><strong>{trace.model}</strong><span className={trace.status}>{trace.status}</span><span>{trace.latency}ms</span><span>{trace.tokens}</span><span>${trace.cost.toFixed(5)}</span><span>{trace.fallbacks}</span></article>)}</div></section></>}
 </div>}
