"use client";
import{useEffect,useMemo,useState}from"react";
import Link from"next/link";
import{defaultVariables,findVariables,interpolate,playgroundPresets}from"@/lib/playground";
import{defaultPlaygroundModels,getPlaygroundModel,playgroundModels}from"@/lib/playground-models";

type Format="text"|"json"|"markdown";type Language="javascript"|"python"|"curl";
type RunResult={modelId:string;name:string;provider:string;status:"success"|"error";response:string;latencyMs:number;inputTokens:number;outputTokens:number;cost:number;error?:string};
const money=(value:number)=>value===0?"FREE":value<.01?`$${value.toFixed(4)}`:`$${value.toFixed(2)}`;

export function PromptPlayground(){
 const first=playgroundPresets[0];
 const[selectedPreset,setSelectedPreset]=useState(first.id);const[selectedModels,setSelectedModels]=useState(defaultPlaygroundModels);const[system,setSystem]=useState(first.system);const[prompt,setPrompt]=useState(first.prompt);const[format,setFormat]=useState<Format>(first.format);const[temperature,setTemperature]=useState(first.temperature);const[maxTokens,setMaxTokens]=useState(Math.min(first.maxTokens,1600));const[variables,setVariables]=useState<Record<string,string>>(defaultVariables);const[language,setLanguage]=useState<Language>("javascript");const[copied,setCopied]=useState(false);const[running,setRunning]=useState(false);const[results,setResults]=useState<RunResult[]>([]);const[runError,setRunError]=useState("");const[winner,setWinner]=useState("");const[apiKey,setApiKey]=useState("");const[gatewayActive,setGatewayActive]=useState<boolean|null>(null);
 useEffect(()=>{fetch("/api/playground/run").then(response=>response.json()).then(body=>setGatewayActive(Boolean(body.gatewayActive))).catch(()=>setGatewayActive(false))},[]);
 const activePreset=playgroundPresets.find(item=>item.id===selectedPreset)??first;const primary=getPlaygroundModel(winner||selectedModels[0])??playgroundModels[0];const variableNames=useMemo(()=>findVariables(`${system}\n${prompt}`),[system,prompt]);const resolvedSystem=interpolate(system,variables);const resolvedPrompt=interpolate(prompt,variables);const inputTokens=Math.max(1,Math.ceil((resolvedSystem.length+resolvedPrompt.length)/4));const maxCost=selectedModels.reduce((sum,id)=>{const model=getPlaygroundModel(id);return sum+(model?(inputTokens*model.inputPrice+maxTokens*model.outputPrice)/1_000_000:0)},0);
 const payload={model:primary.id,messages:[{role:"system",content:resolvedSystem},{role:"user",content:resolvedPrompt}],temperature,max_tokens:maxTokens,...(format==="json"?{response_format:{type:"json_object"}}:{})};const payloadJson=JSON.stringify(payload,null,2);const payloadPython=payloadJson.replace(/\btrue\b/g,"True").replace(/\bfalse\b/g,"False").replace(/\bnull\b/g,"None");const snippets:Record<Language,string>={javascript:`const response = await fetch("https://openrouter.ai/api/v1/chat/completions", {\n  method: "POST",\n  headers: {\n    "Authorization": \`Bearer \${process.env.OPENROUTER_API_KEY}\`,\n    "Content-Type": "application/json"\n  },\n  body: JSON.stringify(${payloadJson})\n});\n\nconsole.log(await response.json());`,python:`import os, requests\n\npayload = ${payloadPython}\nresponse = requests.post(\n    "https://openrouter.ai/api/v1/chat/completions",\n    headers={"Authorization": f"Bearer {os.environ['OPENROUTER_API_KEY']}"},\n    json=payload,\n)\nprint(response.json())`,curl:`curl https://openrouter.ai/api/v1/chat/completions \\\n+  -H "Authorization: Bearer $OPENROUTER_API_KEY" \\\n+  -H "Content-Type: application/json" \\\n+  -d '${payloadJson}'`};
 const applyPreset=(id:string)=>{const preset=playgroundPresets.find(item=>item.id===id);if(!preset)return;setSelectedPreset(id);setSystem(preset.system);setPrompt(preset.prompt);setFormat(preset.format);setTemperature(preset.temperature);setMaxTokens(Math.min(preset.maxTokens,1600));setResults([]);setWinner("")};
 const toggleModel=(id:string)=>{setResults([]);setWinner("");setSelectedModels(current=>current.includes(id)?current.length<=2?current:current.filter(item=>item!==id):current.length>=4?current:[...current,id])};
 const run=async()=>{setRunning(true);setRunError("");setResults([]);setWinner("");try{const response=await fetch("/api/playground/run",{method:"POST",headers:{"content-type":"application/json",...(apiKey?{"x-openrouter-key":apiKey}:{})},body:JSON.stringify({models:selectedModels,system:resolvedSystem,prompt:resolvedPrompt,temperature,maxTokens,format})});const body=await response.json();if(!response.ok)throw new Error(body.error||"The comparison could not run");setResults(body.results??[])}catch(error){setRunError(error instanceof Error?error.message:"The comparison could not run")}finally{setRunning(false)}};
 const copy=async()=>{await navigator.clipboard.writeText(snippets[language]);setCopied(true);window.setTimeout(()=>setCopied(false),1600)};
 return <div className="prompt-lab">
  <aside className="lab-presets"><span>STEP 1 / CHOOSE YOUR GOAL</span><h2>Start with the result you need.</h2>{playgroundPresets.map((preset,index)=><button className={selectedPreset===preset.id?"selected":""} aria-pressed={selectedPreset===preset.id} type="button" key={preset.id} onClick={()=>applyPreset(preset.id)}><small>0{index+1} / {preset.eyebrow}</small><b>{preset.label}</b><p>{preset.description}</p><i>{selectedPreset===preset.id?"SELECTED ✓":"USE THIS GOAL ↗"}</i></button>)}<p>Choosing a goal fills the lab with a working example. Every word and setting remains editable.</p></aside>
  <section className="lab-workspace">
   <div className="lab-toolbar"><div><span>STEP 2 / CUSTOMIZE THE REQUEST</span><h2>Tell every model what good work looks like.</h2><p>Current goal: <b>{activePreset.label}</b> · Result: <b>{activePreset.deliverable}</b></p></div></div>
   <div className="lab-editor-help"><article><b>SYSTEM INSTRUCTION</b><p>Sets the role, standards, and rules shared by every tested model.</p></article><article><b>YOUR TASK</b><p>The exact job each selected model receives, so the comparison stays fair.</p></article></div>
   <div className="lab-editor-grid"><label><span>SYSTEM INSTRUCTION</span><textarea value={system} onChange={event=>{setSystem(event.target.value);setResults([])}} rows={7}/></label><label><span>YOUR TASK / PROMPT</span><textarea value={prompt} onChange={event=>{setPrompt(event.target.value);setResults([])}} rows={11}/></label></div>
   {variableNames.length>0&&<div className="lab-variables"><header><span>FILL IN YOUR DETAILS</span><small>Replace these example values. The final prompt updates automatically.</small></header><div>{variableNames.map(name=><label key={name}><span>{name.replace(/-/g," ").toUpperCase()}</span><input aria-label={`Value for ${name}`} value={variables[name]??""} onChange={event=>{setVariables(current=>({...current,[name]:event.target.value}));setResults([])}}/></label>)}</div></div>}
   <div className="lab-controls"><label><span>ANSWER STYLE</span><small>How every response should be formatted.</small><select value={format} onChange={event=>{setFormat(event.target.value as Format);setResults([])}}><option value="text">Plain text</option><option value="markdown">Markdown with headings</option><option value="json">Structured JSON data</option></select></label><label><span>CREATIVITY <b>{temperature.toFixed(1)}</b></span><small>0 = predictable · 1 = more varied</small><input type="range" min="0" max="1" step="0.1" value={temperature} onChange={event=>{setTemperature(Number(event.target.value));setResults([])}}/></label><label><span>ANSWER LIMIT <b>{maxTokens}</b></span><small>Maximum response length per model.</small><input type="range" min="200" max="1600" step="100" value={maxTokens} onChange={event=>{setMaxTokens(Number(event.target.value));setResults([])}}/></label></div>
  </section>
  <section className="model-test-stage">
   <header><div><span>STEP 3 / SELECT + RUN REAL MODELS</span><h2>Send the same request to two to four models.</h2><p>Responses run independently through Netlify AI Gateway. The model names, outputs, time, token usage, and cost are returned from the live requests.</p></div><div className="run-budget"><small>MAXIMUM ESTIMATED TOTAL</small><strong>{money(maxCost)}</strong><span>{selectedModels.length} models · if every model uses the full answer limit</span></div></header>
   <div className="run-model-picker">{playgroundModels.map(model=>{const selected=selectedModels.includes(model.id);return <button type="button" aria-pressed={selected} className={selected?"selected":""} onClick={()=>toggleModel(model.id)} key={model.id}><span>{model.tier}</span><b>{model.name}</b><small>{model.provider} · {model.context} context</small><p>{model.note}</p><i>{selected?"IN TEST ✓":"ADD TO TEST +"}</i></button>})}</div>
   <div className={`gateway-access ${gatewayActive?"active":"visitor-key"}`}><div><span>MODEL CONNECTION</span><strong>{gatewayActive?"SITE AI GATEWAY READY":"USE YOUR OPENROUTER KEY"}</strong><p>{gatewayActive?"The site gateway is active. You can run the selected models without entering a provider key.":"This Netlify project does not currently provide shared AI credits. Enter your own OpenRouter key to run real models; it stays only in this browser tab and is never saved."}</p></div>{!gatewayActive&&<label><span>OPENROUTER API KEY</span><input type="password" autoComplete="off" placeholder="sk-or-…" value={apiKey} onChange={event=>setApiKey(event.target.value)}/><small>Sent only with the Run request. <a href="https://openrouter.ai/settings/keys" target="_blank" rel="noopener noreferrer">Create or manage a key ↗</a></small></label>}</div>
   <div className="run-action"><div><b>READY TO TEST</b><p>{selectedModels.map(id=>getPlaygroundModel(id)?.name).join(" vs ")}</p></div><button type="button" onClick={run} disabled={running||gatewayActive===false&&!apiKey}>{running?"RUNNING LIVE MODELS…":gatewayActive===false&&!apiKey?"ENTER A KEY TO RUN":"RUN SIDE-BY-SIDE TEST →"}</button></div>{runError&&<div className="run-error" role="alert"><b>TEST COULD NOT RUN</b><p>{runError}</p></div>}
   {results.length>0&&<div className="live-results"><header><span>LIVE RESULTS</span><h3>Compare the answers—not only the model names.</h3><p>Read every response, compare measured usage and speed, then mark the strongest answer for this exact task.</p></header><div className="result-grid">{results.map((result,index)=><article className={`${result.status} ${winner===result.modelId?"winner":""}`} key={result.modelId}><header><span>0{index+1} / {result.provider}</span><h4>{result.name}</h4></header>{result.status==="success"?<><div className="result-stats"><span><b>{(result.latencyMs/1000).toFixed(1)}s</b> TIME</span><span><b>{result.inputTokens+result.outputTokens}</b> TOKENS</span><span><b>{money(result.cost)}</b> COST</span></div><div className="model-answer">{result.response}</div><button type="button" onClick={()=>setWinner(result.modelId)}>{winner===result.modelId?"BEST ANSWER SELECTED ✓":"MARK AS BEST ANSWER"}</button></>:<div className="result-failure"><b>MODEL ERROR</b><p>{result.error}</p></div>}</article>)}</div></div>}
  </section>
  <section className="lab-inspector">
   <header><div><span>STEP 4 / REVIEW + EXPORT THE WINNER</span><h2>{winner?`${primary.name} is selected.`:"Choose the strongest result, then export it."}</h2><p>{winner?"The code below now uses the winning model and your completed prompt.":"Run the test and mark a best answer. Until then, export uses the first selected model."}</p></div><Link href="/benchmarks">CHECK BENCHMARK EVIDENCE ↗</Link></header>
   <div className="lab-metrics"><article><span>PROMPT SIZE</span><strong>{inputTokens.toLocaleString()}</strong><small>estimated input tokens</small></article><article><span>ANSWER LIMIT</span><strong>{maxTokens.toLocaleString()}</strong><small>maximum tokens per model</small></article><article><span>MODELS IN TEST</span><strong>{selectedModels.length}</strong><small>same request and settings</small></article><article><span>EXPORT MODEL</span><strong>{primary.name}</strong><small>{primary.provider} · {primary.tier}</small></article></div>
   <div className="resolved-prompt"><span>FINAL PROMPT PREVIEW<small>The same completed text is sent to every model in the live comparison.</small></span><div><small>MODEL ROLE + RULES</small><p>{resolvedSystem}</p><small>YOUR COMPLETED TASK</small><p>{resolvedPrompt}</p></div></div>
   <div className="code-export"><header><div><span>EXPORT THE WINNING CONFIGURATION</span><h3>Run it in your own project.</h3><p>Choose a language and copy the request. Keep provider keys in environment variables—never in browser code or source control.</p></div><nav>{(["javascript","python","curl"]as Language[]).map(item=><button className={language===item?"active":""} type="button" key={item} onClick={()=>setLanguage(item)}>{item}</button>)}</nav></header><pre><code>{snippets[language]}</code></pre><button className="copy-code" type="button" onClick={copy}>{copied?"CODE COPIED":"COPY WINNING REQUEST"} ↗</button></div>
   <div className="lab-disclosure"><b>LIVE TESTING + PRIVACY</b><p>Running sends the completed prompt to the selected model providers. Site-gateway requests use Netlify AI Gateway; visitor-key requests pass through the protected function to OpenRouter. Keys are held in component memory only and are never written to storage or returned by the server. Do not submit secrets or personal data. Model output can be inaccurate and must be reviewed.</p></div>
  </section>
 </div>
}
