"use client";
import{useMemo,useState}from"react";
import Link from"next/link";
import{compareModels}from"@/lib/comparison";
import{defaultVariables,findVariables,interpolate,playgroundPresets}from"@/lib/playground";

type Format="text"|"json"|"markdown";type Language="javascript"|"python"|"curl";
const money=(value:number)=>value<.01?`$${value.toFixed(4)}`:`$${value.toFixed(2)}`;

export function PromptPlayground(){
 const first=playgroundPresets[0];const[selectedPreset,setSelectedPreset]=useState(first.id);const[modelSlug,setModelSlug]=useState("gpt-5-6-sol");const[system,setSystem]=useState(first.system);const[prompt,setPrompt]=useState(first.prompt);const[format,setFormat]=useState<Format>(first.format);const[temperature,setTemperature]=useState(first.temperature);const[maxTokens,setMaxTokens]=useState(first.maxTokens);const[variables,setVariables]=useState<Record<string,string>>(defaultVariables);const[language,setLanguage]=useState<Language>("javascript");const[copied,setCopied]=useState(false);
 const model=compareModels.find(item=>item.slug===modelSlug)??compareModels[0];const variableNames=useMemo(()=>findVariables(`${system}\n${prompt}`),[system,prompt]);const resolvedSystem=interpolate(system,variables);const resolvedPrompt=interpolate(prompt,variables);const inputTokens=Math.max(1,Math.ceil((resolvedSystem.length+resolvedPrompt.length)/4));const inputCost=model.inputPrice===null?null:inputTokens/1_000_000*model.inputPrice;const outputCost=model.outputPrice===null?null:maxTokens/1_000_000*model.outputPrice;const total=inputCost===null||outputCost===null?null:inputCost+outputCost;
 const payload={model:model.slug,input:[{role:"system",content:resolvedSystem},{role:"user",content:resolvedPrompt}],temperature,max_output_tokens:maxTokens,...(format==="json"?{text:{format:{type:"json_object"}}}:{})};const payloadJson=JSON.stringify(payload,null,2);const payloadPython=payloadJson.replace(/\btrue\b/g,"True").replace(/\bfalse\b/g,"False").replace(/\bnull\b/g,"None");
 const snippets:Record<Language,string>={javascript:`import OpenAI from "openai";\n\nconst client = new OpenAI();\nconst response = await client.responses.create(${payloadJson});\n\nconsole.log(response.output_text);`,python:`from openai import OpenAI\n\nclient = OpenAI()\nresponse = client.responses.create(**${payloadPython})\n\nprint(response.output_text)`,curl:`curl https://api.openai.com/v1/responses \\\n  -H "Authorization: Bearer $API_KEY" \\\n  -H "Content-Type: application/json" \\\n  -d '${payloadJson}'`};
 const applyPreset=(id:string)=>{const preset=playgroundPresets.find(item=>item.id===id);if(!preset)return;setSelectedPreset(id);setSystem(preset.system);setPrompt(preset.prompt);setFormat(preset.format);setTemperature(preset.temperature);setMaxTokens(preset.maxTokens)};const activePreset=playgroundPresets.find(item=>item.id===selectedPreset)??first;
 const copy=async()=>{await navigator.clipboard.writeText(snippets[language]);setCopied(true);window.setTimeout(()=>setCopied(false),1600)};
 return <div className="prompt-lab">
  <aside className="lab-presets"><span>STEP 1 / CHOOSE YOUR GOAL</span><h2>Start with the result you need.</h2>{playgroundPresets.map((preset,index)=><button className={selectedPreset===preset.id?"selected":""} aria-pressed={selectedPreset===preset.id} type="button" key={preset.id} onClick={()=>applyPreset(preset.id)}><small>0{index+1} / {preset.eyebrow}</small><b>{preset.label}</b><p>{preset.description}</p><i>{selectedPreset===preset.id?"SELECTED ✓":"USE THIS GOAL ↗"}</i></button>)}<p>Choosing a goal fills the playground with a strong example. You can change every word and setting.</p></aside>
  <section className="lab-workspace">
   <div className="lab-toolbar"><div><span>STEP 2 / CUSTOMIZE THE REQUEST</span><h2>Tell the model what good work looks like.</h2><p>Current goal: <b>{activePreset.label}</b> · Result: <b>{activePreset.deliverable}</b></p></div><label><b>WHICH MODEL WILL RUN IT?</b><small>This changes the cost and context information below.</small><select value={modelSlug} onChange={event=>setModelSlug(event.target.value)}>{compareModels.map(item=><option value={item.slug} key={item.slug}>{item.name}</option>)}</select></label></div>
   <div className="lab-editor-help"><article><b>SYSTEM INSTRUCTION</b><p>Sets the model’s role, standards, and rules for the whole task.</p></article><article><b>YOUR TASK</b><p>Describes the exact result you want the model to produce.</p></article></div>
   <div className="lab-editor-grid"><label><span>SYSTEM INSTRUCTION</span><textarea aria-describedby="system-help" value={system} onChange={event=>setSystem(event.target.value)} rows={7}/></label><label><span>YOUR TASK / PROMPT</span><textarea aria-describedby="prompt-help" value={prompt} onChange={event=>setPrompt(event.target.value)} rows={11}/></label></div>
   {variableNames.length>0&&<div className="lab-variables"><header><span>FILL IN YOUR DETAILS</span><small>Text inside double braces becomes an editable value. Replace the examples below; the final prompt updates automatically.</small></header><div>{variableNames.map(name=><label key={name}><span>{name.replace(/-/g," ").toUpperCase()}</span><input aria-label={`Value for ${name}`} value={variables[name]??""} onChange={event=>setVariables(current=>({...current,[name]:event.target.value}))}/></label>)}</div></div>}
   <div className="lab-controls"><label><span>ANSWER STYLE</span><small>Choose how the result should be formatted.</small><select value={format} onChange={event=>setFormat(event.target.value as Format)}><option value="text">Plain text</option><option value="markdown">Markdown with headings</option><option value="json">Structured JSON data</option></select></label><label><span>CREATIVITY <b>{temperature.toFixed(1)}</b></span><small>0 = predictable · 1 = more varied</small><input type="range" min="0" max="1" step="0.1" value={temperature} onChange={event=>setTemperature(Number(event.target.value))}/></label><label><span>ANSWER LIMIT <b>{maxTokens}</b></span><small>Maximum response length in tokens.</small><input type="range" min="200" max="4000" step="100" value={maxTokens} onChange={event=>setMaxTokens(Number(event.target.value))}/></label></div>
  </section>
  <section className="lab-inspector">
   <header><div><span>STEP 3 / REVIEW BEFORE USING</span><h2>Here is exactly what you have built.</h2><p>These figures are planning estimates—not a bill and not a generated AI response.</p></div><Link href={`/benchmarks/models/${model.slug}`}>CHECK {model.name.toUpperCase()} EVIDENCE ↗</Link></header>
   <div className="lab-metrics"><article><span>PROMPT SIZE</span><strong>{inputTokens.toLocaleString()}</strong><small>estimated input tokens</small></article><article><span>ANSWER LIMIT</span><strong>{maxTokens.toLocaleString()}</strong><small>maximum output tokens</small></article><article><span>MAXIMUM EST. COST</span><strong>{total===null?"N/A":money(total)}</strong><small>{total===null?"price unavailable":"if the full answer limit is used"}</small></article><article><span>MODEL CAPACITY</span><strong>{model.context}</strong><small>{model.provider} · {model.access}</small></article></div>
   <div className="resolved-prompt"><span>FINAL PROMPT PREVIEW<small>This is the complete text that will be sent when you run the exported code.</small></span><div><small>MODEL ROLE + RULES</small><p>{resolvedSystem}</p><small>YOUR COMPLETED TASK</small><p>{resolvedPrompt}</p></div></div>
   <div className="code-export"><header><div><span>STEP 4 / COPY THE REQUEST</span><h3>Run it in your own project.</h3><p>Choose your language, copy the code, replace the example model identifier if required, and use your provider key only in your secure environment.</p></div><nav>{(["javascript","python","curl"]as Language[]).map(item=><button className={language===item?"active":""} type="button" key={item} onClick={()=>setLanguage(item)}>{item}</button>)}</nav></header><pre><code>{snippets[language]}</code></pre><button className="copy-code" type="button" onClick={copy}>{copied?"CODE COPIED":"COPY CODE TO CLIPBOARD"} ↗</button></div>
   <div className="lab-disclosure"><b>SAFE BY DESIGN</b><p>This browser-only lab does not execute inference, collect API keys, or transmit prompt content. Token counts are estimates and cost uses the recorded benchmark price snapshot. Replace the sample model identifier and validate current provider documentation before running exported code.</p></div>
  </section>
 </div>
}
