"use client";
import{useMemo,useState}from"react";
import Link from"next/link";
import{compareModels}from"@/lib/comparison";
import{defaultVariables,findVariables,interpolate,playgroundPresets}from"@/lib/playground";

type Format="text"|"json"|"markdown";type Language="javascript"|"python"|"curl";
const money=(value:number)=>value<.01?`$${value.toFixed(4)}`:`$${value.toFixed(2)}`;

export function PromptPlayground(){
 const first=playgroundPresets[0];const[modelSlug,setModelSlug]=useState("gpt-5-6-sol");const[system,setSystem]=useState(first.system);const[prompt,setPrompt]=useState(first.prompt);const[format,setFormat]=useState<Format>(first.format);const[temperature,setTemperature]=useState(first.temperature);const[maxTokens,setMaxTokens]=useState(first.maxTokens);const[variables,setVariables]=useState<Record<string,string>>(defaultVariables);const[language,setLanguage]=useState<Language>("javascript");const[copied,setCopied]=useState(false);
 const model=compareModels.find(item=>item.slug===modelSlug)??compareModels[0];const variableNames=useMemo(()=>findVariables(`${system}\n${prompt}`),[system,prompt]);const resolvedSystem=interpolate(system,variables);const resolvedPrompt=interpolate(prompt,variables);const inputTokens=Math.max(1,Math.ceil((resolvedSystem.length+resolvedPrompt.length)/4));const inputCost=model.inputPrice===null?null:inputTokens/1_000_000*model.inputPrice;const outputCost=model.outputPrice===null?null:maxTokens/1_000_000*model.outputPrice;const total=inputCost===null||outputCost===null?null:inputCost+outputCost;
 const payload={model:model.slug,input:[{role:"system",content:resolvedSystem},{role:"user",content:resolvedPrompt}],temperature,max_output_tokens:maxTokens,...(format==="json"?{text:{format:{type:"json_object"}}}:{})};const payloadJson=JSON.stringify(payload,null,2);const payloadPython=payloadJson.replace(/\btrue\b/g,"True").replace(/\bfalse\b/g,"False").replace(/\bnull\b/g,"None");
 const snippets:Record<Language,string>={javascript:`import OpenAI from "openai";\n\nconst client = new OpenAI();\nconst response = await client.responses.create(${payloadJson});\n\nconsole.log(response.output_text);`,python:`from openai import OpenAI\n\nclient = OpenAI()\nresponse = client.responses.create(**${payloadPython})\n\nprint(response.output_text)`,curl:`curl https://api.openai.com/v1/responses \\\n  -H "Authorization: Bearer $API_KEY" \\\n  -H "Content-Type: application/json" \\\n  -d '${payloadJson}'`};
 const applyPreset=(id:string)=>{const preset=playgroundPresets.find(item=>item.id===id);if(!preset)return;setSystem(preset.system);setPrompt(preset.prompt);setFormat(preset.format);setTemperature(preset.temperature);setMaxTokens(preset.maxTokens)};
 const copy=async()=>{await navigator.clipboard.writeText(snippets[language]);setCopied(true);window.setTimeout(()=>setCopied(false),1600)};
 return <div className="prompt-lab">
  <aside className="lab-presets"><span>01 / STARTING POINT</span><h2>Choose a workflow.</h2>{playgroundPresets.map((preset,index)=><button type="button" key={preset.id} onClick={()=>applyPreset(preset.id)}><small>0{index+1} / {preset.eyebrow}</small><b>{preset.label}</b><i>↗</i></button>)}<p>Presets are editable starting points. Nothing is sent to a model from this page.</p></aside>
  <section className="lab-workspace">
   <div className="lab-toolbar"><div><span>02 / CONFIGURE</span><h2>Shape the request.</h2></div><label>MODEL<select value={modelSlug} onChange={event=>setModelSlug(event.target.value)}>{compareModels.map(item=><option value={item.slug} key={item.slug}>{item.name}</option>)}</select></label></div>
   <div className="lab-editor-grid"><label><span>SYSTEM INSTRUCTION</span><textarea value={system} onChange={event=>setSystem(event.target.value)} rows={7}/></label><label><span>USER PROMPT</span><textarea value={prompt} onChange={event=>setPrompt(event.target.value)} rows={11}/></label></div>
   {variableNames.length>0&&<div className="lab-variables"><header><span>VARIABLES</span><small>Reusable values detected from double braces.</small></header><div>{variableNames.map(name=><label key={name}><span>{`{{${name}}}`}</span><input value={variables[name]??""} onChange={event=>setVariables(current=>({...current,[name]:event.target.value}))}/></label>)}</div></div>}
   <div className="lab-controls"><label><span>OUTPUT FORMAT</span><select value={format} onChange={event=>setFormat(event.target.value as Format)}><option value="text">Plain text</option><option value="markdown">Markdown</option><option value="json">JSON object</option></select></label><label><span>TEMPERATURE <b>{temperature.toFixed(1)}</b></span><input type="range" min="0" max="1" step="0.1" value={temperature} onChange={event=>setTemperature(Number(event.target.value))}/></label><label><span>MAX OUTPUT <b>{maxTokens}</b></span><input type="range" min="200" max="4000" step="100" value={maxTokens} onChange={event=>setMaxTokens(Number(event.target.value))}/></label></div>
  </section>
  <section className="lab-inspector">
   <header><div><span>03 / INSPECT</span><h2>Know the request before it runs.</h2></div><Link href={`/benchmarks/models/${model.slug}`}>MODEL EVIDENCE ↗</Link></header>
   <div className="lab-metrics"><article><span>EST. INPUT</span><strong>{inputTokens.toLocaleString()}</strong><small>tokens · character heuristic</small></article><article><span>MAX OUTPUT</span><strong>{maxTokens.toLocaleString()}</strong><small>tokens · configured ceiling</small></article><article><span>EST. MAX COST</span><strong>{total===null?"N/A":money(total)}</strong><small>{total===null?"pricing not recorded":"input + maximum output"}</small></article><article><span>CONTEXT</span><strong>{model.context}</strong><small>{model.provider} · {model.access}</small></article></div>
   <div className="resolved-prompt"><span>RESOLVED REQUEST</span><div><small>SYSTEM</small><p>{resolvedSystem}</p><small>USER</small><p>{resolvedPrompt}</p></div></div>
   <div className="code-export"><header><div><span>04 / EXPORT</span><h3>Move into your stack.</h3></div><nav>{(["javascript","python","curl"]as Language[]).map(item=><button className={language===item?"active":""} type="button" key={item} onClick={()=>setLanguage(item)}>{item}</button>)}</nav></header><pre><code>{snippets[language]}</code></pre><button className="copy-code" type="button" onClick={copy}>{copied?"COPIED":"COPY REQUEST"} ↗</button></div>
   <div className="lab-disclosure"><b>SAFE BY DESIGN</b><p>This browser-only lab does not execute inference, collect API keys, or transmit prompt content. Token counts are estimates and cost uses the recorded benchmark price snapshot. Replace the sample model identifier and validate current provider documentation before running exported code.</p></div>
  </section>
 </div>
}
