export type Price="Free"|"Freemium"|"Paid"|"Open source";
export type Audience="Developer"|"Creative";
export type Tool={slug:string;name:string;company:string;summary:string;category:string;price:Price;audience:Audience;bestFor:string[];url:string;mark:string;featured?:boolean};
export const tools:Tool[]=[
 {slug:"openai-api",name:"OpenAI API",company:"OpenAI",summary:"Multimodal reasoning, generation, voice, and agent capabilities through one developer platform.",category:"Foundation model",price:"Paid",audience:"Developer",bestFor:["Agents","Multimodal apps","Automation"],url:"https://platform.openai.com/",mark:"OA",featured:true},
 {slug:"gemini-api",name:"Gemini API",company:"Google",summary:"Long-context multimodal models with an accessible prototyping path and broad Google ecosystem support.",category:"Foundation model",price:"Freemium",audience:"Developer",bestFor:["Long context","Media understanding","Prototypes"],url:"https://ai.google.dev/",mark:"GE",featured:true},
 {slug:"claude-api",name:"Claude API",company:"Anthropic",summary:"Reasoning and coding models designed for complex knowledge work, analysis, and agentic systems.",category:"Foundation model",price:"Paid",audience:"Developer",bestFor:["Coding","Documents","Agents"],url:"https://docs.anthropic.com/",mark:"CL"},
 {slug:"hugging-face",name:"Hugging Face",company:"Community",summary:"Discover, evaluate, and deploy open models, datasets, demos, and inference services.",category:"Model platform",price:"Freemium",audience:"Developer",bestFor:["Open models","Research","Deployment"],url:"https://huggingface.co/",mark:"HF"},
 {slug:"ollama",name:"Ollama",company:"Ollama",summary:"Run and manage open models locally through a focused command-line and API workflow.",category:"Local runtime",price:"Open source",audience:"Developer",bestFor:["Privacy","Local AI","Testing"],url:"https://ollama.com/",mark:"OL"},
 {slug:"mistral",name:"Mistral AI",company:"Mistral",summary:"Efficient open and commercial language models with developer-first inference APIs.",category:"Foundation model",price:"Freemium",audience:"Developer",bestFor:["Multilingual","Efficiency","Agents"],url:"https://mistral.ai/",mark:"MI"},
 {slug:"firefly",name:"Adobe Firefly",company:"Adobe",summary:"Generate and edit images, video, and design assets inside familiar professional creative workflows.",category:"Creative suite",price:"Freemium",audience:"Creative",bestFor:["Photography","Design","Production"],url:"https://firefly.adobe.com/",mark:"FF",featured:true},
 {slug:"runway",name:"Runway",company:"Runway",summary:"Generative video, transformation, and production tools built for filmmakers and visual storytellers.",category:"Generative video",price:"Freemium",audience:"Creative",bestFor:["Video","Motion","VFX"],url:"https://runwayml.com/",mark:"RW",featured:true},
 {slug:"davinci-resolve",name:"DaVinci Resolve",company:"Blackmagic Design",summary:"Professional editing, color, audio, and neural tools in one production environment.",category:"Post-production",price:"Free",audience:"Creative",bestFor:["Editing","Color","Audio"],url:"https://www.blackmagicdesign.com/products/davinciresolve",mark:"DR"},
 {slug:"canva",name:"Canva Magic Studio",company:"Canva",summary:"Fast AI-assisted design, layouts, media creation, and brand production for everyday content.",category:"Design platform",price:"Freemium",audience:"Creative",bestFor:["Social","Design","Brand kits"],url:"https://www.canva.com/magic-studio/",mark:"CA"},
 {slug:"topaz",name:"Topaz Photo",company:"Topaz Labs",summary:"Specialized denoise, sharpening, upscaling, and image recovery for demanding photo work.",category:"Photo enhancement",price:"Paid",audience:"Creative",bestFor:["Denoise","Upscale","Restore"],url:"https://www.topazlabs.com/",mark:"TZ"},
 {slug:"capcut",name:"CapCut",company:"ByteDance",summary:"Accessible video editing with AI captions, cleanup, effects, and social-first workflows.",category:"Video editor",price:"Freemium",audience:"Creative",bestFor:["Short video","Captions","Social"],url:"https://www.capcut.com/",mark:"CC"},
];
export const developerTools=tools.filter(tool=>tool.audience==="Developer");
export const creativeTools=tools.filter(tool=>tool.audience==="Creative");
export const featuredTools=tools.filter(tool=>tool.featured);
