import{getPlaygroundModel}from"./playground-models";
export type TaskType="general"|"coding"|"reasoning"|"classification"|"creative"|"extraction";
export type RouteRule={id:string;name:string;enabled:boolean;task:TaskType|"any";keywords:string[];minChars:number;maxChars:number;modelId:string;reason:string};
export type RoutingPolicy={id:string;name:string;description:string;maxCost:number;maxLatency:number;fallbacks:string[];rules:RouteRule[];defaultModel:string;createdAt:string};
export type RouteDecision={modelId:string;ruleId:string|null;ruleName:string;reason:string;matched:string[];estimatedInputTokens:number;estimatedOutputTokens:number;estimatedCost:number;budgetStatus:"within"|"over";fallbacks:string[];trace:{label:string;value:string;status:"pass"|"skip"|"info"}[]};
export const taskOptions:TaskType[]=["general","coding","reasoning","classification","creative","extraction"];
const now="2026-08-20T00:00:00.000Z";
export const routingTemplates:RoutingPolicy[]=[
 {id:"balanced",name:"Balanced production router",description:"Use compact models for routine work and escalate complex requests.",maxCost:.025,maxLatency:12000,defaultModel:"google/gemini-3.7-flash",fallbacks:["z-ai/glm-5.3","nvidia/nemotron-3.5-lightning:free"],createdAt:now,rules:[
  {id:"classify",name:"Fast classification",enabled:true,task:"classification",keywords:["classify","label","category","sentiment"],minChars:0,maxChars:4000,modelId:"nvidia/nemotron-3.5-lightning:free",reason:"A compact free route is sufficient for bounded classification."},
  {id:"code",name:"Software work",enabled:true,task:"coding",keywords:["code","function","debug","sql","typescript","python"],minChars:0,maxChars:12000,modelId:"deepseek/deepseek-v4-pro-0813",reason:"Route implementation and debugging work to the open coding specialist."},
  {id:"complex",name:"Complex reasoning",enabled:true,task:"reasoning",keywords:["analyze","strategy","trade-off","architecture","prove"],minChars:800,maxChars:12000,modelId:"google/gemini-3.7-flash",reason:"Escalate longer analytical work to the frontier reasoning route."}
 ]},
 {id:"cost",name:"Cost-first router",description:"Prefer free and moderate-cost routes unless the task explicitly requires reasoning.",maxCost:.008,maxLatency:16000,defaultModel:"nvidia/nemotron-3.5-lightning:free",fallbacks:["qwen/qwen3.8-27b","google/gemini-3.7-flash"],createdAt:now,rules:[
  {id:"reasoning",name:"Reasoning escalation",enabled:true,task:"reasoning",keywords:["reason","analyze","compare","architecture"],minChars:600,maxChars:12000,modelId:"qwen/qwen3.8-27b",reason:"Use a moderate-cost open model when the request needs explicit reasoning."},
  {id:"creative",name:"Creative production",enabled:true,task:"creative",keywords:["campaign","story","creative","script","concept"],minChars:0,maxChars:12000,modelId:"qwen/qwen3.8-27b",reason:"Creative work receives a capable open model while staying inside the cost ceiling."}
 ]},
 {id:"quality",name:"Quality-first router",description:"Prefer frontier capability, retaining open-model fallbacks for resilience.",maxCost:.08,maxLatency:20000,defaultModel:"google/gemini-3.7-flash",fallbacks:["deepseek/deepseek-v4-pro-0813","z-ai/glm-5.3"],createdAt:now,rules:[
  {id:"code",name:"Deep code path",enabled:true,task:"coding",keywords:["repository","debug","implementation","security"],minChars:500,maxChars:12000,modelId:"deepseek/deepseek-v4-pro-0813",reason:"Use the coding-oriented model for substantive software requests."},
  {id:"long",name:"Long-context analysis",enabled:true,task:"any",keywords:[],minChars:2500,maxChars:12000,modelId:"google/gemini-3.7-flash",reason:"Long prompts remain on the frontier route for stronger synthesis."}
 ]}
];
export const defaultPolicy=routingTemplates[0];
export const clonePolicy=(policy:RoutingPolicy):RoutingPolicy=>JSON.parse(JSON.stringify({...policy,id:`policy-${Date.now()}`,createdAt:new Date().toISOString()}));
export function routeRequest(policy:RoutingPolicy,prompt:string,task:TaskType,maxTokens:number):RouteDecision{const normalized=prompt.toLowerCase();const chars=prompt.length;const trace:RouteDecision["trace"]=[];let selected:RouteRule|undefined;for(const rule of policy.rules){if(!rule.enabled){trace.push({label:rule.name,value:"Disabled",status:"skip"});continue}const taskMatch=rule.task==="any"||rule.task===task;const lengthMatch=chars>=rule.minChars&&chars<=rule.maxChars;const matched=rule.keywords.filter(keyword=>normalized.includes(keyword.toLowerCase()));const keywordMatch=!rule.keywords.length||matched.length>0;const passes=taskMatch&&lengthMatch&&keywordMatch;trace.push({label:rule.name,value:passes?`Matched${matched.length?`: ${matched.join(", ")}`:""}`:`Skipped · ${!taskMatch?"task":!lengthMatch?"length":"keywords"}`,status:passes?"pass":"skip"});if(passes&&!selected)selected=rule}const modelId=selected?.modelId??policy.defaultModel;const model=getPlaygroundModel(modelId);const estimatedInputTokens=Math.max(1,Math.ceil(chars/4));const estimatedOutputTokens=Math.max(100,maxTokens);const estimatedCost=model?(estimatedInputTokens*model.inputPrice+estimatedOutputTokens*model.outputPrice)/1_000_000:0;trace.push({label:"Budget guard",value:`$${estimatedCost.toFixed(5)} estimated / $${policy.maxCost.toFixed(3)} maximum`,status:estimatedCost<=policy.maxCost?"pass":"skip"});trace.push({label:"Final route",value:model?.name??modelId,status:"info"});return{modelId,ruleId:selected?.id??null,ruleName:selected?.name??"Default route",reason:selected?.reason??"No higher-priority rule matched, so the policy default was selected.",matched:selected?.keywords.filter(keyword=>normalized.includes(keyword.toLowerCase()))??[],estimatedInputTokens,estimatedOutputTokens,estimatedCost,budgetStatus:estimatedCost<=policy.maxCost?"within":"over",fallbacks:policy.fallbacks.filter(id=>id!==modelId),trace}}
export const exportPolicy=(policy:RoutingPolicy)=>({version:1,kind:"axon-radar-routing-policy",...policy});
