type Category="Frontier"|"Open source"|"Agents"|"Research"|"Creative"|"Business"|"Robotics"|"Policy";
type Item={id:string;title:string;summary:string;source:string;url:string;publishedAt:string;category:Category};
type SourceHealth={name:string;ok:boolean;count:number};
const feeds=[
 {name:"OpenAI",url:"https://openai.com/news/rss.xml",category:"Frontier" as Category},
 {name:"Hugging Face",url:"https://huggingface.co/blog/feed.xml",category:"Open source" as Category},
 {name:"NVIDIA Developer",url:"https://developer.nvidia.com/blog/feed/",category:"Research" as Category},
 {name:"Google Research",url:"https://research.google/blog/rss/",category:"Research" as Category},
 {name:"Microsoft Research",url:"https://www.microsoft.com/en-us/research/feed/",category:"Research" as Category},
 {name:"AWS Machine Learning",url:"https://aws.amazon.com/blogs/machine-learning/feed/",category:"Agents" as Category},
];
const namedEntities:Record<string,string>={amp:"&",apos:"'",quot:'"',lt:"<",gt:">",nbsp:" ",ndash:"–",mdash:"—",hellip:"…",lsquo:"‘",rsquo:"’",ldquo:"“",rdquo:"”"};
const decodeEntities=(value:string)=>value.replace(/&(#x[\da-f]+|#\d+|[a-z]+);/gi,(entity,code:string)=>{if(code[0]==="#"){const point=code[1]?.toLowerCase()==="x"?Number.parseInt(code.slice(2),16):Number.parseInt(code.slice(1),10);return Number.isFinite(point)?String.fromCodePoint(point):entity}return namedEntities[code.toLowerCase()]??entity});
const clean=(value:string)=>{let text=value.replace(/<!\[CDATA\[|\]\]>/g,"");for(let pass=0;pass<3;pass+=1){text=decodeEntities(text).replace(/<!--[\s\S]*?-->/g," ").replace(/<(script|style|svg)[^>]*>[\s\S]*?<\/\1>/gi," ").replace(/<\/?[a-z][^>]*>/gi," ")}return decodeEntities(text).replace(/\s+/g," ").replace(/^[-–—|:;\s]+/,"").trim()};
const tag=(xml:string,names:string[])=>{for(const name of names){const value=xml.match(new RegExp(`<${name}(?:\\s[^>]*)?>([\\s\\S]*?)<\\/${name}>`,"i"))?.[1];if(value)return clean(value)}return""};
const categoryFor=(title:string,summary:string,fallback:Category):Category=>{const text=`${title} ${summary}`.toLowerCase();if(/agent|copilot|coding/.test(text))return"Agents";if(/image|video|creative|design|audio|film/.test(text))return"Creative";if(/robot|autonomous|humanoid/.test(text))return"Robotics";if(/policy|regulation|safety|governance|law/.test(text))return"Policy";if(/funding|revenue|enterprise|company|partnership|acquisition/.test(text))return"Business";if(/open.source|open weight|hugging face|ollama/.test(text))return"Open source";if(/model|gpt|gemini|claude|llama|mistral|deepseek/.test(text))return"Frontier";return fallback};
function parseFeed(xml:string,source:string,fallback:Category):Item[]{const blocks=[...xml.matchAll(/<(?:item|entry)(?:\s[^>]*)?>([\s\S]*?)<\/(?:item|entry)>/gi)];return blocks.slice(0,18).map((match,index)=>{const block=match[1];const title=tag(block,["title"]);const summary=clean(tag(block,["content:encoded","summary","description","content"])).slice(0,520);const directLink=clean(block.match(/<link[^>]+href=["']([^"']+)["'][^>]*>/i)?.[1]??tag(block,["link","guid","id"]));const published=tag(block,["pubDate","published","updated","dc:date"]);const parsedDate=Date.parse(published);return{id:`${source}-${index}-${title}`.replace(/[^a-z0-9-]/gi,"-").slice(0,150),title,summary:summary||`Read ${source}’s complete announcement and technical details at the original link.`,source,url:directLink,publishedAt:new Date(Number.isFinite(parsedDate)?parsedDate:Date.now()).toISOString(),category:categoryFor(title,summary,fallback)}}).filter(item=>item.title&&/^https?:\/\//.test(item.url))}
async function withTimeout(url:string,ms=4500){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),ms);try{return await fetch(url,{headers:{Accept:"application/rss+xml, application/atom+xml, application/xml, text/xml, application/json","User-Agent":"AI-Radar-Newsroom/4.0"},signal:controller.signal,next:{revalidate:300}})}finally{clearTimeout(timer)}}
async function fetchRss(feed:typeof feeds[number]){try{const response=await withTimeout(feed.url);if(!response.ok)return{items:[] as Item[],health:{name:feed.name,ok:false,count:0}};const items=parseFeed(await response.text(),feed.name,feed.category);return{items,health:{name:feed.name,ok:true,count:items.length}}}catch{return{items:[] as Item[],health:{name:feed.name,ok:false,count:0}}}}
async function fetchHackerNews():Promise<{items:Item[];health:SourceHealth}>{try{const since=Math.floor(Date.now()/1000)-60*60*24*14;const url=`https://hn.algolia.com/api/v1/search_by_date?query=AI%20OR%20LLM%20OR%20machine%20learning&tags=story&hitsPerPage=60&numericFilters=created_at_i%3E${since}`;const response=await withTimeout(url);if(!response.ok)return{items:[],health:{name:"Hacker News",ok:false,count:0}};const data=await response.json() as {hits?:Array<{objectID:string;title?:string;story_title?:string;url?:string;story_url?:string;story_text?:string;created_at?:string;author?:string;num_comments?:number}>};const items=(data.hits??[]).map(hit=>{const title=hit.title??hit.story_title??"";const url=hit.url??hit.story_url??`https://news.ycombinator.com/item?id=${hit.objectID}`;const body=clean(hit.story_text??"");const summary=body.slice(0,520)||`A current AI story submitted by ${hit.author??"the Hacker News community"}, with ${hit.num_comments??0} discussion comments. Open the source for the complete report and discussion.`;return{id:`hn-${hit.objectID}`,title,summary,source:"Hacker News",url,publishedAt:new Date(hit.created_at??Date.now()).toISOString(),category:categoryFor(title,summary,"Business")}}).filter(item=>item.title&&/^https?:\/\//.test(item.url));return{items,health:{name:"Hacker News",ok:true,count:items.length}}}catch{return{items:[],health:{name:"Hacker News",ok:false,count:0}}}}
export async function GET(){const results=await Promise.all([...feeds.map(fetchRss),fetchHackerNews()]);const health=results.map(result=>result.health);const seen=new Set<string>();const items=results.flatMap(result=>result.items).sort((a,b)=>Date.parse(b.publishedAt)-Date.parse(a.publishedAt)).filter(item=>{const key=item.title.toLowerCase().replace(/[^a-z0-9]/g,"").slice(0,100);if(seen.has(key))return false;seen.add(key);return true}).slice(0,100);return Response.json({items,meta:{updatedAt:new Date().toISOString(),total:items.length,liveSources:health.filter(source=>source.ok).length,totalSources:health.length,health,refreshSeconds:300}},{status:items.length?200:503,headers:{"Cache-Control":items.length?"public, max-age=60, s-maxage=300, stale-while-revalidate=900":"no-store"}})}
